IMPORTING THE DEPENDENCIES

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.pipeline import make_pipeline

Data Collection and Processing

In [2]:
#loadin(g csv data
heart_data=pd.read_csv("heart_disease_data.csv")
# heart_data.describe()

In [3]:
heart_data.shape

(303, 14)

In [4]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [6]:
#cheacking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
#statistical measure about the data
heart_data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [8]:
#checking the distribution of target value
heart_data["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

1---> heart Disease
0---> heart healthy

#### Splitting the Features and Target

In [9]:
#target is colulmn  target
#all others  are our feature
X=heart_data.drop(columns="target",axis=1)
Y=heart_data["target"]

Spliting the data into Training and Test Data

In [10]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [11]:
#check how the data divide 
print(X.shape,X_train.shape,X_test.shape)

(303, 13) (242, 13) (61, 13)


#### Model Training

Logistic Regression Model

In [12]:
model=LogisticRegression()

In [13]:
#training the Logistic Regression model with Training the data
model.fit(X_train,Y_train)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#### Model Evaluation

Accureccy score

In [14]:
#accuracy on training data
X_train_Prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_Prediction,Y_train)

In [15]:
print('Accuracy on Training Data:',training_data_accuracy)

Accuracy on Training Data: 0.8512396694214877


In [16]:
#accuracy on test data
X_test_Prediction=model.predict(X_test )
test_data_accuracy=accuracy_score(X_test_Prediction,Y_test)

In [17]:
print('Accuracy on Test Data:',test_data_accuracy)


Accuracy on Test Data: 0.819672131147541


#### Building The Predicting System

In [18]:
# 50,1,0,150,243,0,0,128,0,2.6,1,0,3
# 55,0,1,132,342,0,1,166,0,1.2,2,0,2

input_data=(55,0,1,132,342,0,1,166,0,1.2,2,0,2)
#change input data to numpy array
data_numpy_array=np.asarray(input_data)
# reshape the numpy array as we are predicting for only on instance

input_data_reshaped=data_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [19]:
prediction

array([1], dtype=int64)

In [20]:
if prediction==1:
    print("You have a heart disease")
elif prediction==0:
    print("You have a healthy heart")

You have a heart disease


pickle try

In [23]:
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [22]:
import pickle


In [71]:
ohe=OneHotEncoder()
ohe.fit(X[["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal"]])

OneHotEncoder()

In [72]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal"]),
                                    remainder='passthrough')

In [73]:
lr=LogisticRegression()

In [74]:
pipe=make_pipeline(column_trans,lr)

In [75]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([29, 34, 35, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 74, 76, 77], dtype=int64),
                                                                            array([0, 1], dtype=int64),
                                                                            array([0, 1, 2, 3], dtype=int64),
                                                                            array([ 94, 100, 10...
                                                                            array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.8, 2.9, 3. , 3.1, 3.2, 3.4, 3.5, 3.6, 3.8, 4. , 4.2, 4.4, 5.6,
       6.2]),
                                                                            array([0, 1, 2], dtype=int64),
                                                                            array([0, 1, 2, 3, 4], dtype=int64),
                                                                            array([0, 1, 2, 3], dtype=int64)]),
                                                  ['age', 'sex', 'cp',
                                                   'trestbps', 'chol', 'fbs',
                                                   'restecg', 'thalach',
                                                   'exang', 'oldpeak', 'slope',
                                                   'ca', 'thal'])])),
                ('logisticregression', LogisticRegression())])

In [76]:
Y_pred=pipe.predict(X_test)

In [77]:
Y_pred

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [78]:
pickle.dump(pipe,open("LogisticRegressionModel.pkl","wb"))

In [82]:
Prediction=pipe.predict(pd.DataFrame([[55,0,1,132,342,0,1,166,0,1.2,2,0,2]],columns=["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal"]))

In [83]:
Prediction

array([1], dtype=int64)

In [84]:
if prediction==1:
    print("You have a heart disease")
elif prediction==0:
    print("You have a healthy heart")

You have a heart disease
